sudo: false
language: python
matrix:
    include:
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=py27
            python: 2.7
        # https://github.com/deadsnakes/travis-ci-python3.7-example
        -   env: TOXENV=py37
            sudo: required
            dist: xenial
            addons:
              apt:
                sources:
                  - sourceline: 'ppa:deadsnakes/ppa'
                packages:
                  - python3.7-dev
install: pip install tox
script: tox
cache:
    directories:
        - $HOME/.cache/pip
